services:
  - type: web
    name: llama-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OLLAMA_BASE_URL
        value: https://7afdc15e5ab0.ngrok-free.app
    plan: free
